version: "3"
services:
  con1:
    image: constellation:0.2.0
    container_name: constellation1
    ports:
      - "9001:9000"
    volumes: 
      - ./qdata/dd1/constellation:/etc/constellation
  con2:
    image: constellation:0.2.0
    container_name: constellation2
    ports:
      - "9002:9000"
    volumes: 
      - ./qdata/dd2/constellation:/etc/constellation
  con3:
    image: constellation:0.2.0
    container_name: constellation3
    ports:
      - "9003:9000"
    volumes: 
      - ./qdata/dd3/constellation:/etc/constellation
  con4:
    image: constellation:0.2.0
    container_name: constellation4
    ports:
      - "9004:9000"
    volumes: 
      - ./qdata/dd4/constellation:/etc/constellation
  con5:
    image: constellation:0.2.0
    container_name: constellation5
    ports:
      - "9005:9000"
    volumes: 
      - ./qdata/dd5/constellation:/etc/constellation
  con6:
    image: constellation:0.2.0
    container_name: constellation6
    ports:
      - "9006:9000"
    volumes: 
      - ./qdata/dd6/constellation:/etc/constellation
  con7:
    image: constellation:0.2.0
    container_name: constellation7
    ports:
      - "9007:9000"
    volumes: 
      - ./qdata/dd7/constellation:/etc/constellation      
networks:
  default:
    external:
      name: quorum-network
